import inspect
from .registries.devops_test import registry

"""
Input list example:

[
    {"function": "add_numbers", "args": {"a": 2, "b": 3}, "assign": "sum"},
    {"function": "log_message", "args": {"message": "Result: {sum}"}}
]
"""

def compile_plan(plan):
    code = "# Generated by AGX\n\n"

    # get unique functions to avoid duplicates
    unique_functions = set()
    for step in plan:
        unique_functions.add(step["function"])

    # Insert source of dependent functions without duplicates
    for func_name in unique_functions:
        code += inspect.getsource(registry[func_name]) + "\n"
    
    # main logic
    code += "def main():\n"

    for step in plan:
        func_name = step["function"] # Required
        args = step.get("args", {}) # Optional
        assign = step.get("assign") # Optional

        processed_args = []
        for k, v in args.items():
            if isinstance(v, str) and "{" in v and "}" in v:
                # Convert "Result: {sum}" to f"Result: {sum}"
                processed_args.append(f'{k}=f"{v}"')
            else:
                processed_args.append(f"{k}={repr(v)}")

        args_str = ", ".join(processed_args)

        if assign:
            code += f"    {assign} = {func_name}({args_str})\n"
        else:
            code += f"    {func_name}({args_str})\n"
    
    code += '\nif __name__ == "__main__":\n    main()\n'

    return code